version: '2'

networks:
  front:
  back:

services:

  node:
    image: node
    links:
      - backend
    ports:
     - "9000:9000"
    networks:
     - front
     - back
     
     
  backend:
    build: backend/
    ports:
      - "9000:9000"
    environment:
      - APPID=88510c0ca4c7d0e4f0ade76c22e6c641
      - TARGET_CITY=Tampere,fi
    networks:
      - back

  frontend:
    build: frontend/
    ports:
      - "8000:8000"
    environment:
      - ENDPOINT=http://localhost:9000
    networks:
      - front
