version: '2'

services:  
     
  backend:
    build: backend/
    ports:
      - "9000:9000"
    environment:
      - APPID=
      - TARGET_CITY=Tampere,fi

  frontend:
    build: frontend/
    ports:
      - "8000:8000"
    environment:
      - ENDPOINT=http://localhost:9000
    links:
      - backend
